export const RANDOM_TEXTS = [
  "Bienvenidos a Momento Mate",
  "Sucribete y siguenos en nuestras redes",
  "Prepara un mate y únete a la conversación",
  "Usualmente somos cuatro, hoy somos una banda",
  "La web esta naasheee",
  "¿Preparado para el Momento eso?",
  "No te olvides de dejar tu saludo para Matías, el mate",
  "¿Trajeron criollos?",
  "**Ruido de mate**",
  "Recalculando... ¡Acabas de ingresar a Momento Mate!",
  "Más mate, menos problemas. ¿Quién se suma?",
  "La vida es mejor con amigos y mates. ¡Hagamos ambas cosas!",
  "No somos adictos al mate, solo le tenemos cariño exagerado",
  "Los amigos son como el mate: a veces amargos, a veces dulces, pero siempre necesarios.",
  "¿Ya vieron el último reel en instagram? Es la clave",
  "Tomate un mate y olvídate",
  "Que buen día para un Mate, Matecito, Matuco, Materete, Matarazzo, Materodáctilo",
  "Puto el que lee",
];